// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.30.2
// source: jobs.proto

package jobs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	Status_Started Status = 0
	Status_Exited  Status = 1
	Status_Killed  Status = 2
	Status_Error   Status = 3
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "Started",
		1: "Exited",
		2: "Killed",
		3: "Error",
	}
	Status_value = map[string]int32{
		"Started": 0,
		"Exited":  1,
		"Killed":  2,
		"Error":   3,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_jobs_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_jobs_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_jobs_proto_rawDescGZIP(), []int{0}
}

type OutputReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OutputReq) Reset() {
	*x = OutputReq{}
	mi := &file_jobs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutputReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutputReq) ProtoMessage() {}

func (x *OutputReq) ProtoReflect() protoreflect.Message {
	mi := &file_jobs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutputReq.ProtoReflect.Descriptor instead.
func (*OutputReq) Descriptor() ([]byte, []int) {
	return file_jobs_proto_rawDescGZIP(), []int{0}
}

func (x *OutputReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type OutputResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Out           []byte                 `protobuf:"bytes,1,opt,name=out,proto3" json:"out,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OutputResp) Reset() {
	*x = OutputResp{}
	mi := &file_jobs_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutputResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutputResp) ProtoMessage() {}

func (x *OutputResp) ProtoReflect() protoreflect.Message {
	mi := &file_jobs_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutputResp.ProtoReflect.Descriptor instead.
func (*OutputResp) Descriptor() ([]byte, []int) {
	return file_jobs_proto_rawDescGZIP(), []int{1}
}

func (x *OutputResp) GetOut() []byte {
	if x != nil {
		return x.Out
	}
	return nil
}

type PingMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingMsg) Reset() {
	*x = PingMsg{}
	mi := &file_jobs_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingMsg) ProtoMessage() {}

func (x *PingMsg) ProtoReflect() protoreflect.Message {
	mi := &file_jobs_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingMsg.ProtoReflect.Descriptor instead.
func (*PingMsg) Descriptor() ([]byte, []int) {
	return file_jobs_proto_rawDescGZIP(), []int{2}
}

type StatusReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusReq) Reset() {
	*x = StatusReq{}
	mi := &file_jobs_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusReq) ProtoMessage() {}

func (x *StatusReq) ProtoReflect() protoreflect.Message {
	mi := &file_jobs_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusReq.ProtoReflect.Descriptor instead.
func (*StatusReq) Descriptor() ([]byte, []int) {
	return file_jobs_proto_rawDescGZIP(), []int{3}
}

func (x *StatusReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type StatusLine struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	User          string                 `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	Command       []string               `protobuf:"bytes,3,rep,name=command,proto3" json:"command,omitempty"`
	Status        Status                 `protobuf:"varint,4,opt,name=status,proto3,enum=tpworker.jobs.Status" json:"status,omitempty"`
	Exitcode      int32                  `protobuf:"varint,5,opt,name=exitcode,proto3" json:"exitcode,omitempty"`
	Started       int64                  `protobuf:"varint,6,opt,name=started,proto3" json:"started,omitempty"`
	Stopped       int64                  `protobuf:"varint,7,opt,name=stopped,proto3" json:"stopped,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusLine) Reset() {
	*x = StatusLine{}
	mi := &file_jobs_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusLine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusLine) ProtoMessage() {}

func (x *StatusLine) ProtoReflect() protoreflect.Message {
	mi := &file_jobs_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusLine.ProtoReflect.Descriptor instead.
func (*StatusLine) Descriptor() ([]byte, []int) {
	return file_jobs_proto_rawDescGZIP(), []int{4}
}

func (x *StatusLine) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *StatusLine) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *StatusLine) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *StatusLine) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_Started
}

func (x *StatusLine) GetExitcode() int32 {
	if x != nil {
		return x.Exitcode
	}
	return 0
}

func (x *StatusLine) GetStarted() int64 {
	if x != nil {
		return x.Started
	}
	return 0
}

func (x *StatusLine) GetStopped() int64 {
	if x != nil {
		return x.Stopped
	}
	return 0
}

type StatusResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Statusline    []*StatusLine          `protobuf:"bytes,1,rep,name=statusline,proto3" json:"statusline,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResp) Reset() {
	*x = StatusResp{}
	mi := &file_jobs_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResp) ProtoMessage() {}

func (x *StatusResp) ProtoReflect() protoreflect.Message {
	mi := &file_jobs_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResp.ProtoReflect.Descriptor instead.
func (*StatusResp) Descriptor() ([]byte, []int) {
	return file_jobs_proto_rawDescGZIP(), []int{5}
}

func (x *StatusResp) GetStatusline() []*StatusLine {
	if x != nil {
		return x.Statusline
	}
	return nil
}

type StartReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cmd           []string               `protobuf:"bytes,1,rep,name=cmd,proto3" json:"cmd,omitempty"`
	Env           []string               `protobuf:"bytes,2,rep,name=env,proto3" json:"env,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartReq) Reset() {
	*x = StartReq{}
	mi := &file_jobs_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartReq) ProtoMessage() {}

func (x *StartReq) ProtoReflect() protoreflect.Message {
	mi := &file_jobs_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartReq.ProtoReflect.Descriptor instead.
func (*StartReq) Descriptor() ([]byte, []int) {
	return file_jobs_proto_rawDescGZIP(), []int{6}
}

func (x *StartReq) GetCmd() []string {
	if x != nil {
		return x.Cmd
	}
	return nil
}

func (x *StartReq) GetEnv() []string {
	if x != nil {
		return x.Env
	}
	return nil
}

type StartResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartResp) Reset() {
	*x = StartResp{}
	mi := &file_jobs_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartResp) ProtoMessage() {}

func (x *StartResp) ProtoReflect() protoreflect.Message {
	mi := &file_jobs_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartResp.ProtoReflect.Descriptor instead.
func (*StartResp) Descriptor() ([]byte, []int) {
	return file_jobs_proto_rawDescGZIP(), []int{7}
}

func (x *StartResp) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type StopReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopReq) Reset() {
	*x = StopReq{}
	mi := &file_jobs_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopReq) ProtoMessage() {}

func (x *StopReq) ProtoReflect() protoreflect.Message {
	mi := &file_jobs_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopReq.ProtoReflect.Descriptor instead.
func (*StopReq) Descriptor() ([]byte, []int) {
	return file_jobs_proto_rawDescGZIP(), []int{8}
}

func (x *StopReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type StopResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cmd           string                 `protobuf:"bytes,1,opt,name=cmd,proto3" json:"cmd,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopResp) Reset() {
	*x = StopResp{}
	mi := &file_jobs_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopResp) ProtoMessage() {}

func (x *StopResp) ProtoReflect() protoreflect.Message {
	mi := &file_jobs_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopResp.ProtoReflect.Descriptor instead.
func (*StopResp) Descriptor() ([]byte, []int) {
	return file_jobs_proto_rawDescGZIP(), []int{9}
}

func (x *StopResp) GetCmd() string {
	if x != nil {
		return x.Cmd
	}
	return ""
}

func (x *StopResp) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_jobs_proto protoreflect.FileDescriptor

const file_jobs_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"jobs.proto\x12\rtpworker.jobs\"\x1b\n" +
	"\tOutputReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x1e\n" +
	"\n" +
	"OutputResp\x12\x10\n" +
	"\x03out\x18\x01 \x01(\fR\x03out\"\t\n" +
	"\aPingMsg\"\x1b\n" +
	"\tStatusReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xc9\x01\n" +
	"\n" +
	"StatusLine\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04user\x18\x02 \x01(\tR\x04user\x12\x18\n" +
	"\acommand\x18\x03 \x03(\tR\acommand\x12-\n" +
	"\x06status\x18\x04 \x01(\x0e2\x15.tpworker.jobs.StatusR\x06status\x12\x1a\n" +
	"\bexitcode\x18\x05 \x01(\x05R\bexitcode\x12\x18\n" +
	"\astarted\x18\x06 \x01(\x03R\astarted\x12\x18\n" +
	"\astopped\x18\a \x01(\x03R\astopped\"G\n" +
	"\n" +
	"StatusResp\x129\n" +
	"\n" +
	"statusline\x18\x01 \x03(\v2\x19.tpworker.jobs.StatusLineR\n" +
	"statusline\".\n" +
	"\bStartReq\x12\x10\n" +
	"\x03cmd\x18\x01 \x03(\tR\x03cmd\x12\x10\n" +
	"\x03env\x18\x02 \x03(\tR\x03env\"\x1b\n" +
	"\tStartResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x19\n" +
	"\aStopReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\",\n" +
	"\bStopResp\x12\x10\n" +
	"\x03cmd\x18\x01 \x01(\tR\x03cmd\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id*8\n" +
	"\x06Status\x12\v\n" +
	"\aStarted\x10\x00\x12\n" +
	"\n" +
	"\x06Exited\x10\x01\x12\n" +
	"\n" +
	"\x06Killed\x10\x02\x12\t\n" +
	"\x05Error\x10\x032\xbd\x02\n" +
	"\x04Jobs\x12A\n" +
	"\x06Output\x12\x18.tpworker.jobs.OutputReq\x1a\x19.tpworker.jobs.OutputResp\"\x000\x01\x128\n" +
	"\x04Ping\x12\x16.tpworker.jobs.PingMsg\x1a\x16.tpworker.jobs.PingMsg\"\x00\x12?\n" +
	"\x06Status\x12\x18.tpworker.jobs.StatusReq\x1a\x19.tpworker.jobs.StatusResp\"\x00\x12<\n" +
	"\x05Start\x12\x17.tpworker.jobs.StartReq\x1a\x18.tpworker.jobs.StartResp\"\x00\x129\n" +
	"\x04Stop\x12\x16.tpworker.jobs.StopReq\x1a\x17.tpworker.jobs.StopResp\"\x00B\x16Z\x14tp-worker/proto/jobsb\x06proto3"

var (
	file_jobs_proto_rawDescOnce sync.Once
	file_jobs_proto_rawDescData []byte
)

func file_jobs_proto_rawDescGZIP() []byte {
	file_jobs_proto_rawDescOnce.Do(func() {
		file_jobs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_jobs_proto_rawDesc), len(file_jobs_proto_rawDesc)))
	})
	return file_jobs_proto_rawDescData
}

var file_jobs_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_jobs_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_jobs_proto_goTypes = []any{
	(Status)(0),        // 0: tpworker.jobs.Status
	(*OutputReq)(nil),  // 1: tpworker.jobs.OutputReq
	(*OutputResp)(nil), // 2: tpworker.jobs.OutputResp
	(*PingMsg)(nil),    // 3: tpworker.jobs.PingMsg
	(*StatusReq)(nil),  // 4: tpworker.jobs.StatusReq
	(*StatusLine)(nil), // 5: tpworker.jobs.StatusLine
	(*StatusResp)(nil), // 6: tpworker.jobs.StatusResp
	(*StartReq)(nil),   // 7: tpworker.jobs.StartReq
	(*StartResp)(nil),  // 8: tpworker.jobs.StartResp
	(*StopReq)(nil),    // 9: tpworker.jobs.StopReq
	(*StopResp)(nil),   // 10: tpworker.jobs.StopResp
}
var file_jobs_proto_depIdxs = []int32{
	0,  // 0: tpworker.jobs.StatusLine.status:type_name -> tpworker.jobs.Status
	5,  // 1: tpworker.jobs.StatusResp.statusline:type_name -> tpworker.jobs.StatusLine
	1,  // 2: tpworker.jobs.Jobs.Output:input_type -> tpworker.jobs.OutputReq
	3,  // 3: tpworker.jobs.Jobs.Ping:input_type -> tpworker.jobs.PingMsg
	4,  // 4: tpworker.jobs.Jobs.Status:input_type -> tpworker.jobs.StatusReq
	7,  // 5: tpworker.jobs.Jobs.Start:input_type -> tpworker.jobs.StartReq
	9,  // 6: tpworker.jobs.Jobs.Stop:input_type -> tpworker.jobs.StopReq
	2,  // 7: tpworker.jobs.Jobs.Output:output_type -> tpworker.jobs.OutputResp
	3,  // 8: tpworker.jobs.Jobs.Ping:output_type -> tpworker.jobs.PingMsg
	6,  // 9: tpworker.jobs.Jobs.Status:output_type -> tpworker.jobs.StatusResp
	8,  // 10: tpworker.jobs.Jobs.Start:output_type -> tpworker.jobs.StartResp
	10, // 11: tpworker.jobs.Jobs.Stop:output_type -> tpworker.jobs.StopResp
	7,  // [7:12] is the sub-list for method output_type
	2,  // [2:7] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_jobs_proto_init() }
func file_jobs_proto_init() {
	if File_jobs_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_jobs_proto_rawDesc), len(file_jobs_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_jobs_proto_goTypes,
		DependencyIndexes: file_jobs_proto_depIdxs,
		EnumInfos:         file_jobs_proto_enumTypes,
		MessageInfos:      file_jobs_proto_msgTypes,
	}.Build()
	File_jobs_proto = out.File
	file_jobs_proto_goTypes = nil
	file_jobs_proto_depIdxs = nil
}
